# Generated by Django 6.1 on 2026-08-10 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('phone_no', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('is_disposable', models.BooleanField(default=False)),
                ('quantity_available', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Challan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_type', models.CharField(choices=[('quotation', 'Quotation-based (Initiation Form)'), ('hand', 'Hand Challan')], max_length=20)),
                ('challan_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('billed_company', models.CharField(blank=True, max_length=255, verbose_name='Billed Company (or Firm)')),
                ('contact_name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('is_quotation_based', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('void', 'Void')], default='pending', max_length=20)),
                ('void_reason', models.TextField(blank=True)),
                ('challan_no_change_reason', models.TextField(blank=True, verbose_name='Challan No. change reason')),
                ('adjust_requested', models.BooleanField(default=False, verbose_name='Adjust')),
                ('admin_approval_required', models.BooleanField(default=False)),
                ('admin_approved', models.BooleanField(default=False)),
                ('delivered_by', models.CharField(blank=True, max_length=255)),
                ('received_by_name', models.CharField(blank=True, max_length=255)),
                ('received_by_phone', models.CharField(blank=True, max_length=30)),
                ('is_billed_out', models.BooleanField(default=False)),
                ('billed_out_at', models.DateTimeField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('unlocked_by_admin', models.BooleanField(default=False)),
                ('last_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challans_created', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='challans', to='challan.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveIntegerField(verbose_name='S.N.')),
                ('product_name', models.CharField(max_length=255, verbose_name='Item / Goods detail')),
                ('quantity', models.PositiveIntegerField(verbose_name='Qty')),
                ('challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='challan.challan')),
            ],
            options={
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('adjust_requested', models.BooleanField(default=False, verbose_name='Adjust')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challans', models.ManyToManyField(related_name='billing_entries', to='challan.challan')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billings', to='challan.client')),
            ],
            options={
                'verbose_name_plural': 'Billings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeStockChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255)),
                ('delivered_by', models.CharField(blank=True, max_length=255)),
                ('adjust_requested', models.BooleanField(default=False, verbose_name='Adjust')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_stock_challan', to='challan.challan')),
            ],
        ),
        migrations.CreateModel(
            name='StockIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('for_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_intakes', to='challan.client')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intakes', to='challan.stockitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeStockChallanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('employee_stock_challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='challan.employeestockchallan')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='challan.stockitem')),
            ],
        ),
    ]
