# Generated by Django 4.2.26 on 2026-08-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0002_challan_extension_days_alter_billing_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='personal_details_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='challan',
            name='personal_details_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
