# Generated by Django 4.2.26 on 2026-08-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0003_challan_personal_details_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='extend_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='challan',
            name='extended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
