# Generated by Django 4.2.26 on 2026-08-14 05:20

from django.db import migrations, models
import django.db.models.deletion


def seed_companies(apps, schema_editor):
    Company = apps.get_model('challan', 'Company')
    office, _ = Company.objects.get_or_create(name="Office", defaults={"code": "O"})
    Company.objects.get_or_create(name="Store", defaults={"code": "S"})
    Company.objects.get_or_create(name="Maintenance", defaults={"code": "M"})

    Challan = apps.get_model('challan', 'Challan')
    Challan.objects.filter(billed_company__isnull=True).update(billed_company=office)

    Billing = apps.get_model('challan', 'Billing')
    Billing.objects.filter(company_name__isnull=True).update(company_name=office)


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0004_challan_extend_reason_challan_extended_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='billing',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billings', to='challan.company', verbose_name='Specific Company Name'),
        ),
        migrations.AlterField(
            model_name='challan',
            name='billed_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='challans', to='challan.company', verbose_name='Billed Company (or Firm)'),
        ),
        migrations.RunPython(seed_companies),
    ]
