# Generated by Django 4.2.26 on 2026-08-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0005_company_alter_billing_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='void_approved_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challan',
            name='void_requested',
            field=models.BooleanField(default=False, verbose_name='Void Requested'),
        ),
    ]
