# Generated by Django 4.2.26 on 2026-08-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0006_challan_void_approved_by_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='adjust_reason',
            field=models.TextField(blank=True, verbose_name='Adjustment / Replacement Details'),
        ),
    ]
