# Generated by Django 4.2.26 on 2026-08-24 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0007_challan_adjust_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeestockchallanitem',
            name='employee_stock_challan',
        ),
        migrations.RemoveField(
            model_name='employeestockchallanitem',
            name='stock_item',
        ),
        migrations.RemoveField(
            model_name='stockintake',
            name='for_client',
        ),
        migrations.AddField(
            model_name='challan',
            name='is_from_stock_intake',
            field=models.BooleanField(default=False, verbose_name='Issue from Stock Intake'),
        ),
        migrations.AddField(
            model_name='challan',
            name='stock_employee_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Employee Name (Stock Intake)'),
        ),
        migrations.AddField(
            model_name='challanitem',
            name='stock_intake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_challan_items', to='challan.stockintake'),
        ),
        migrations.AddField(
            model_name='stockintake',
            name='employee_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Employee Name'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EmployeeStockChallan',
        ),
        migrations.DeleteModel(
            name='EmployeeStockChallanItem',
        ),
    ]
