# Generated by Django 4.2.26 on 2026-08-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0008_remove_employeestockchallanitem_employee_stock_challan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='bill_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bill No.'),
        ),
    ]
