# Generated by Django 4.2.26 on 2026-08-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0009_billing_bill_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='company',
            name='pan_vat_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='PAN / VAT No.'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Phone Number'),
        ),
    ]
