# Generated by Django 4.2.26 on 2026-08-24 07:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0010_company_address_company_pan_vat_no_company_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockintake',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Intake Date'),
        ),
    ]
