# Generated by Django 4.2.26 on 2026-08-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0011_alter_stockintake_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockintake',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
    ]
