# Generated by Django 4.2.26 on 2026-08-24 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0012_stockintake_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Billing Date'),
        ),
        migrations.AlterField(
            model_name='challan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date'),
        ),
    ]
