# Generated by Django 4.2.26 on 2026-08-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0013_alter_billing_created_at_alter_challan_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='challanitem',
            name='actual_qty',
            field=models.PositiveIntegerField(blank=True, help_text='Quantity actually received/confirmed by client (only for adjustments)', null=True, verbose_name='Actual Qty'),
        ),
        migrations.AddField(
            model_name='challanitem',
            name='adjusted_qty',
            field=models.PositiveIntegerField(blank=True, help_text='Auto-calculated: Original Qty − Actual Qty', null=True, verbose_name='Adjusted Qty'),
        ),
    ]
