# Generated by Django 4.2.26 on 2026-08-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0015_challanitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='unit',
            field=models.CharField(blank=True, choices=[('pcs', 'pcs'), ('roll', 'roll'), ('set', 'set'), ('pkt', 'pkt'), ('meter', 'meter'), ('box', 'box'), ('kg', 'kg'), ('bundle', 'bundle'), ('pair', 'pair')], default='pcs', max_length=20, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='challanitem',
            name='unit',
            field=models.CharField(blank=True, choices=[('pcs', 'pcs'), ('roll', 'roll'), ('set', 'set'), ('pkt', 'pkt'), ('meter', 'meter'), ('box', 'box'), ('kg', 'kg'), ('bundle', 'bundle'), ('pair', 'pair')], default='pcs', max_length=20, verbose_name='Unit'),
        ),
    ]
