# Generated by Django 4.2.26 on 2026-08-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0016_stockitem_unit_alter_challanitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='challanitem',
            name='item_serial_no',
            field=models.CharField(blank=True, max_length=255, verbose_name='Serial No. (S/N)'),
        ),
    ]
