# Generated by Django 4.2.26 on 2026-08-30 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challan', '0017_challanitem_item_serial_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='tada_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='TADA Out Date'),
        ),
        migrations.AddField(
            model_name='billing',
            name='tada_completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tada_outs_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billing',
            name='tada_status',
            field=models.CharField(choices=[('pending', 'Pending (In TADA)'), ('completed', 'TADA Out')], default='pending', max_length=20, verbose_name='TADA Status'),
        ),
    ]
